apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-net-ca
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: hig-carrier
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: carrier-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.8
       
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin
    storage:
      storageclassname: carriersc
      storagesize: 20Gi
    vault:
      role: vault-role
      address: http://vault.dev.carrier.internal.thetech.digital
      authpath: devcarrier-net-auth
      secretcert: carrier/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: carrier/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: carrier/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
      external_url_suffix: carrier.dev.carrier.thetech.digital
