---
- name: "Setting up mongodb cluster"
  include_tasks: "{{ item }}.yaml"
  with_items:
    - "pre-tasks-deploy"
    - "deploy"
  when: action == "mongodb_deploy"

- name: "Cleanup mongodb cluster"
  include_tasks: "{{ item }}.yaml"
  with_items:
    - "pre-tasks-cleanup.yaml"
    - "cleanup.yaml"
  when: action == "mongodb_cleanup"