---
- name: "Setting up mongodb cluster"
  include_tasks: "{{ item }}.yaml"
  with_items:
    - "pre-tasks-deploy"
    - "deploy"
  when: deploy_action == "mongodb-deploy"

- name: "Cleanup mongodb cluster"
  include_tasks: "{{ item }}.yaml"
  with_items:
    - "pre-tasks-cleanup"
    - "cleanup"
  when: deploy_action == "mongodb-cleanup"