apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: install-openidl-cc-default-v1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: install-openidl-cc-default-v1
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: develop-jenkins
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: carrier-net
      network:
        version: 2.2.3
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.dev.carrier.internal.thetech.digital
      authpath: devcarrier-net-auth
      adminsecretprefix: carrier/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: carrier/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: carrier/credentials/carrier-net/git?git_password
      tls: false
    orderer:
      address: orderer5.ordererorg.dev.aais.thetech.digital:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.3
      name: openidl-cc-default
      version: v1
      lang: golang
      maindirectory: main
      repository:
        hostname: "github.com"
        git_username: ""
        url: github.com/rajeshsanjeevi/openidl-main.git
        branch: develop-jenkins
        path: openidl-chaincode/chaincode/openidl
      endorsementpolicies:  ''
