ordererorg_domain: "aais.thetech.digital"
domain: "aais.thetech.digital"
internal_domain: "aais.internal.thetech.digital"
add_org: ""
chaincode_version: ""
node_type: "aais"
network:
  org_name: "aais"
  ordererorg: "true"
  ordererorg_name: "ordererorg"
  organizations:
    - name: ""
      domain: ""
    - name: ""
      domain: ""
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
