access_id: ""
access_key: ""
region: ""
cluster_name: ""
account: ""
gitops_repo_url: "github.com/rajeshsanjeevi/openidl-iaac.git"
gitops_repo_branch: "hig-carrier"
gitops_repo_user: ""
gitops_repo_user_token: ""
gitops_repo_user_email: ""
ordererorg_domain: "aais.thetech.digital"
domain: "aais.thetech.digital"
internal_domain: "aais.internal.thetech.digital"
env: "dev"
add_org: ""
registry: ""
chaincode_version: ""
node_type: "aais"

network:
    org_name: "aais"
    ordererorg: "true"
    ordererorg_name: "ordererorg"
    organizations:
        - name: "analytics"
          domain: "thetech.digital"
        - name: "carrier"
          domain: "thetech.digital"
    channels:
        - name: analytics-carrier
          chaincode:
              name: openidl-cc-aais-carriers
              repo_url: github.com/rajeshsanjeevi/openidl-main.git
              repo_branch: hig-carrier
              repo_path: openidl-chaincode/chaincode/openidl
              collectionconfig:
                - name: "analytics_carrier_pdc"
                  policy: "OR('analyticsMSP.member', 'carrierMSP.member')"
        - name: analytics-aais
          chaincode:
              name: openidl-cc-aais-carriers
              repo_url: github.com/rajeshsanjeevi/openidl-main.git
              repo_branch: hig-carrier
              repo_path: openidl-chaincode/chaincode/openidl
              collectionconfig:
                - name: "analytics_aais_pdc"
                  policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
        - name: defaultchannel
          chaincode:
              name: openidl-cc-default
              repo_url: github.com/rajeshsanjeevi/openidl-main.git
              repo_branch: hig-carrier
              repo_path: openidl-chaincode/chaincode/openidl
