access_id: ""
access_key: ""
region: ""
cluster_name: ""
account: ""
gitops_repo_url: "github.com/openidl-aais/openidl-aais-gitops"
gitops_repo_branch: "aais_dev"
gitops_repo_user: ""
gitops_repo_user_token: ""
gitops_repo_user_email: ""
ordererorg_domain: "openidl.aaisdirect.com"
domain: "thetech.digital"
internal_domain: "internal.thetech.digital"
env: "dev"
add_org: ""
registry: ""
chaincode_version: ""
node_type: "aais"

network:
    org_name: "aais"
    ordererorg: "true"
    ordererorg_name: "ordererorg"
    organizations:
        - name: "analytics"
          domain: "thetech.digital"
        - name: "carrier"
          domain: "thetech.digital"
    channels:
        - name: defaultchannel
          chaincode:
              name: openidl-cc-default
              repo_url: github.com/openidl-org/openidl-main.git
              repo_branch: develop
              repo_path: openidl-chaincode/chaincode/openidl
        - name: anal-aais
          chaincode:
              name: openidl-cc-aais-carriers
              repo_url: github.com/openidl-org/openidl-main.git
              repo_branch: "develop"
              repo_path: openidl-chaincode/chaincode/openidl
              collectionconfig:
                - name: "analytics_aais_pdc"
                  policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
                - name: "anal_aais_pdc"
                  policy: "OR('analyticsMSP.member', 'aaisMSP.member')"