ordererorg_domain: "aais.thetech.digital"
domain: "analytics.thetech.digital"
internal_domain: "analytics.internal.thetech.digital"
node_type: "analytics"
network:
  org_name: "analytics"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: "carrier"
      domain: "carrier.thtetech.digital"
      org_status: ""
  channels:
  - name: analytics-aais
    chaincode:
      name: openidl-cc-aais-anal
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        name: "analytics_aais_pdc"
        policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
  - name: analytics-carrier
    chaincode:
      name: openidl-cc-aais-carr
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        name: "analytics_carrier_pdc"
        policy: "OR('analyticsMSP.member', 'carrierMSP.member')"
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
