ordererorg_domain: "aais.thetech.digital"
domain: "carrier.thetech.digital"
internal_domain: "carrier.internal.thetech.digital"
add_org: "" 
node_type: "carrier"
network:
  org_name: "carr"
  ordererorg: "false"
  ordererorg_name: "ordererorg"
  organizations:
    - name: "analytics"
      domain: "analytics.thetech.digital"
      org_status: ""
    - name: "carr"
      domain: "carrier.thetech.digital"
      org_status: ""
  channels:
  - name: anal-carr
    chaincode:
      name: openidl-cc-anal-carr
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        name: "analytics_carrier_pdc"
        policy: "OR('analyticsMSP.member', 'carrierMSP.member')"
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: github.com/rajeshsanjeevi/openidl-main.git
      repo_branch: hig-carrier
      repo_path: openidl-chaincode/chaincode/openidl
