- hosts: ansible_provisioners
  gather_facts: yes
  no_log: "{{ no_ansible_log | default(false) }}"
  vars_files:
    - "./{{ org_name }}-config-{{ env }}.yml"

  tasks:
    - include_role:
        name: "prerun-job"
      vars:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        aws_external_id: "{{ aws_external_id }}"
        aws_iam_role: "{{ aws_iam_role }}"
        cluster_name: "{{ app_cluster_name }}"

    - include_role:
        name: "mongodb"
      vars:
        mongodb_user_token: "{{ user_token }}"
        mongodb_user: "{{ network.org_name }}-{{ env }}-{{ user }}"
        mongodb_root_token: "{{ root_token }}"
        mongodb_database: "openidl-offchain-db"
        cluster_name: "{{ app_cluster_name }}"
        action: "{{ action }}"


