apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-aais-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-aais-aais
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: hig-carrier
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: aais-net
      network:
        version 2.2.3
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.aais-net:7051
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.thetech.digital
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: aais
    orderer:
      address: orderer1.ordererorg.dev.aais.thetech.digital:8443
    channeltx: |-
      CpMDChIKEAgCGgYI6sH9jgYiBGFhaXMS/AIK+QIKBGFhaXMSLhIcCgtBcHBsaWNhdGlvbhINEgsK
      B2FhaXNNU1ASABoOCgpDb25zb3J0aXVtEgAawAISmAIKC0FwcGxpY2F0aW9uEogCCAESCwoHYWFp
      c01TUBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIAoGQWRtaW5zEhYS
      DAgDEggKBkFkbWlucxoGQWRtaW5zIioKC0VuZG9yc2VtZW50EhsSEQgDEg0KC0VuZG9yc2VtZW50
      GgZBZG1pbnMiMwoUTGlmZWN5Y2xlRW5kb3JzZW1lbnQSGxIRCAMSDQoLRW5kb3JzZW1lbnQaBkFk
      bWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgD
      EgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGiMKCkNvbnNvcnRpdW0SFRITChFPcGVuSURMQ29u
      c29ydGl1bQ==