apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-aais-anal-carr
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-aais-anal-carr
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: develop-jenkins
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: aais-net
      network:
        version 2.2.3
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.aais-net:7051
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.thetech.digital
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: anal-carr
    orderer:
      address: orderer1.ordererorg.dev.aais.thetech.digital:8443
    channeltx: |-
      Cp0DChcKFQgCGgYIqMeSkAYiCWFuYWwtY2FychKBAwr+AgoJYW5hbC1jYXJyEi4SHAoLQXBwbGlj
      YXRpb24SDRILCgdhYWlzTVNQEgAaDgoKQ29uc29ydGl1bRIAGsACEpgCCgtBcHBsaWNhdGlvbhKI
      AggBEgsKB2FhaXNNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYyXzASABoGQWRtaW5zIioK
      C0VuZG9yc2VtZW50EhsSEQgDEg0KC0VuZG9yc2VtZW50GgZBZG1pbnMiMwoUTGlmZWN5Y2xlRW5k
      b3JzZW1lbnQSGxIRCAMSDQoLRW5kb3JzZW1lbnQaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkK
      B1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyIgCgZB
      ZG1pbnMSFhIMCAMSCAoGQWRtaW5zGgZBZG1pbnMqBkFkbWlucxojCgpDb25zb3J0aXVtEhUSEwoR
      T3BlbklETENvbnNvcnRpdW0=