apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-defaultchannel-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-defaultchannel-aais
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: hig-carrier
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.aais.thetech.digital:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.thetech.digital
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: defaultchannel      
    orderer:
      address: orderer1.ordererorg.dev.aais.thetech.digital:8443
    anchorstx: |-
      CtUCChwKGggCGgYIg4aJjwYiDmRlZmF1bHRjaGFubmVsErQCCrECCg5kZWZhdWx0Y2hhbm5lbBJg
      El4KC0FwcGxpY2F0aW9uEk8IARJLCgdhYWlzTVNQEkAaBwoDTVNQEgAiDwoLRW5kb3JzZW1lbnQS
      ACILCgdSZWFkZXJzEgAiCwoHV3JpdGVycxIAIgoKBkFkbWlucxIAGrwBErkBCgtBcHBsaWNhdGlv
      bhKpAQgBEqQBCgdhYWlzTVNQEpgBCAEaTAoLQW5jaG9yUGVlcnMSPRIzCjEKLHBlZXIwLmFhaXMt
      bmV0LmFhaXMuZGV2LmFhaXMudGhldGVjaC5kaWdpdGFsEPtBGgZBZG1pbnMaBwoDTVNQEgAiCwoH
      V3JpdGVycxIAIgoKBkFkbWlucxIAIg8KC0VuZG9yc2VtZW50EgAiCwoHUmVhZGVycxIAKgZBZG1p
      bnM=

