apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-aais-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-aais-aais
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: hig-carrier
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.aais.thetech.digital:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.thetech.digital
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: aais      
    orderer:
      address: orderer1.ordererorg.dev.aais.thetech.digital:8443
    anchorstx: |-
      CsECChIKEAgCGgYI68H9jgYiBGFhaXMSqgIKpwIKBGFhaXMSYBJeCgtBcHBsaWNhdGlvbhJPCAES
      SwoHYWFpc01TUBJAGgcKA01TUBIAIgsKB1dyaXRlcnMSACIKCgZBZG1pbnMSACIPCgtFbmRvcnNl
      bWVudBIAIgsKB1JlYWRlcnMSABq8ARK5AQoLQXBwbGljYXRpb24SqQEIARKkAQoHYWFpc01TUBKY
      AQgBGkwKC0FuY2hvclBlZXJzEj0SMwoxCixwZWVyMC5hYWlzLW5ldC5hYWlzLmRldi5hYWlzLnRo
      ZXRlY2guZGlnaXRhbBD7QRoGQWRtaW5zGgcKA01TUBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJz
      EgAiCgoGQWRtaW5zEgAiDwoLRW5kb3JzZW1lbnQSACoGQWRtaW5z

