apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: anchorpeer-anal-aais-aais
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: anchorpeer-anal-aais-aais
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: hig-carrier
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/anchorpeer
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.aais-net.aais.dev.aais.thetech.digital:8443
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.thetech.digital
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: anal-aais      
    orderer:
      address: orderer1.ordererorg.dev.aais.thetech.digital:8443
    anchorstx: |-
      CssCChcKFQgCGgYIwb6SjwYiCWFuYWwtYWFpcxKvAgqsAgoJYW5hbC1hYWlzEmASXgoLQXBwbGlj
      YXRpb24STwgBEksKB2FhaXNNU1ASQBoHCgNNU1ASACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAi
      DwoLRW5kb3JzZW1lbnQSACILCgdSZWFkZXJzEgAavAESuQEKC0FwcGxpY2F0aW9uEqkBCAESpAEK
      B2FhaXNNU1ASmAEIARoHCgNNU1ASABpMCgtBbmNob3JQZWVycxI9EjMKMQoscGVlcjAuYWFpcy1u
      ZXQuYWFpcy5kZXYuYWFpcy50aGV0ZWNoLmRpZ2l0YWwQ+0EaBkFkbWlucyIPCgtFbmRvcnNlbWVu
      dBIAIgsKB1JlYWRlcnMSACILCgdXcml0ZXJzEgAiCgoGQWRtaW5zEgAqBkFkbWlucw==

