apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-aais-openidl-cc-aais-anal-1-1
  namespace: aais-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-aais-openidl-cc-aais-anal-1-1
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: hig-carrier
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: aais-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.aais-net:7051
      localmspid: aaisMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://vault.dev.aais.internal.thetech.digital
      authpath: devaais-net-auth
      adminsecretprefix: aais/crypto/peerOrganizations/aais-net/users/admin 
      orderersecretprefix: aais/crypto/peerOrganizations/aais-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.ordererorg.dev.aais.thetech.digital:8443
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.3
      name: openidl-cc-aais-anal
      version: 1
      sequence: 1
      commitarguments: ''
      endorsementpolicies:  ''
      collectionconfig: |-
        WwogIHsKICAgICJuYW1lIjogImFuYWx5dGljc19hYWlzX3BkYyIsCiAgICAicG9saWN5IjogIk9S
        KCdhbmFseXRpY3NNU1AubWVtYmVyJywgJ2FhaXNNU1AubWVtYmVyJykiLAogICAgInJlcXVpcmVk
        UGVlckNvdW50IjogMCwKICAgICJtYXhQZWVyQ291bnQiOiAwLAogICAgImJsb2NrVG9MaXZlIjog
        MAogIH0KXQoK
      usecollectionconfig: true
    channel:
      name: aais
