pipeline {
    agent any
    tools {
        terraform 'terraform'
        git 'git'
    }
    stages {
        stage("init") {
            steps {
                echo "terraform init started"
            }
        }
    }
}
