pipeline {
    agent {
        node {
            label 'Jenkins-Master'
        }
    }
    tools {
        terraform 'terraform'
        git 'git'
    }
    stages {
        stage("init") {
            steps {
                echo "terraform init started"
                sh "terraform -chdir=aws/aws_resources init --backend-config=../tf_s3_backend/aws_resources_tfc.hcl"
                echo "terraform init finished"
                }
        }
    }
}
