---
- name: "Setting up vault cluster"
  include_tasks: "{{ item }}.yaml"
  with_items:
    - "pre-tasks"
    - "deploy"
  when: action == "deploy"

- name: "Cleanup vault cluster"
  include_tasks: "cleanup.yaml"
  when: action == "cleanup"

