- name: Get KMS ID
  shell: |
    export AWS_PROFILE=cicd-role
    aws kms describe-key --key-id alias/{{ network.org_name[:4] }}-{{ env }}-vault-kmskey | jq -r .KeyMetadata.KeyId
  register: output

- set_fact:
    config_user: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

- set_fact:
    config_user_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"

- set_fact:
    kvs_user: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

- set_fact:
    kvs_user_token: "{{ lookup('password', '/dev/null chars=ascii_uppercase,ascii_lowercase,digits length=40') }}"
