apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: join-defaultchannel-carrier-peer0
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: join-defaultchannel-carrier-peer0
  chart:
    git: https://github.com/rajeshsanjeevi/openidl-iaac.git
    ref: hig-carrier
    path: blockchain-automation-framework/platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.3
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.carrier-net.carrier.dev.carrier.thetech.digital:8443
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://vault.dev.carrier.internal.thetech.digital
      authpath: devcarrier-net-auth
      adminsecretprefix: carrier/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: carrier/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: defaultchannel      
    orderer:
      address: orderer1.ordererorg.dev.aais.thetech.digital:8443
