{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "haproxy-ingress.labels" . | nindent 4 }}
  name: {{ include "haproxy-ingress.fullname" . }}
  namespace: {{ .Values.metadata.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "haproxy-ingress.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "haproxy-ingress.serviceAccountName" . }}
    namespace: {{ .Values.metadata.namespace }}
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: {{ include "haproxy-ingress.fullname" . }}
{{- end }}
