# This is a manual workflow, hence it must be placed in the default branch of a repository to activate and use
#Author: Rajesh Sanjeevi
#version: 1.0

name: Manual BAF Deployment
on:
  workflow_dispatch:
    inputs:
      role:
        description: "ansible role name"
        required: true
        default: ""

jobs:
  healthcheck:
    environment: itpc-aais-dev
    name: Healthcheck
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    defaults:
      run:
        shell: bash
        working-directory: openidl-ansible
    env:
      cluster_name: ${{ secrets.blk_cluster_name }}
      aws_region: ${{ secrets.region }}
      aws_access_key: ${{ secrets.git_user_access_key }}
      aws_secret_key: ${{ secrets.git_user_secret_key }}
      aws_account: ${{ secrets.account_number }}
      aws_role: ${{ secrets.iam_role }}
      aws_external_id: ${{ secrets.external_id }}
      github_user: ${{ secrets.ghub_user }}
      github_user_token: ${{ secrets.ghub_user_token }}
      github_user_email: ${{ secrets.ghub_user_email }}
      registry: ghcr.io

    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      
      - name: Print aws info
        run: |
          echo env.aws_region, env.aws_external_id, env.aws_role, env.aws_access_key

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@230d25f14e841bc8e06b5f4ff89ccd6989fc1d71
        with:
          aws-access-key-id: ${{ env.aws_access_key }}
          aws-secret-access-key: ${{ env.aws_secret_key }}
          aws-region: ${{ env.aws_region }}
          role-to-assume: ${{ env.aws_role }}
          role-external-id: ${{ secrets.aws_external_id }}
          role-duration-seconds: 7200 # session valid for 30 minutes
          role-session-name: git-actions
          role-skip-session-tagging: true

      - name: Install Ansible and dependencies
        run: |
          pip3 install openshift
          sudo apt-get install -y python3-requests-oauthlib
          sudo apt-get install -y python-yaml
          python -m pip install --user ansible==2.9.11

      - name: Install ansible galaxy collection for docker and k8s
        run: |
          ansible-galaxy collection install community.docker
          ansible-galaxy collection install community.kubernetes:==1.2.1

      - name: Setup kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Update kubeconfig and set context to blockchain cluster
        run: |
          aws eks update-kubeconfig --region ${{ env.aws_region }} --name ${{ env.cluster_name }}

      - name: Install Docker
        run: |
          pip3 install docker

      - name: Log into GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Playbook
        run: |
         echo "ansible playbook" 
        #  ansible-playbook deploy-network.yml -i ./inventory/ansible_provisioners -e "role=${{ github.event.inputs.role }} package_repo=${{ env.registry }}/${{ github.actor }}/openidl-org/openidl-baf"





