- name: vault-helm-deployment
  hosts: localhost
  become: False
  vars_files:
    - ./group_vars/vault/vars.yaml

  tasks:
    - name: Getting list of clusters
      shell: |
        aws eks list-clusters --region {{ region }}

    - name: Getting kube config file
      shell: |
        aws eks --region {{ region }} update-kubeconfig --name {{ clustername }}

    - name: Getting list of files in .kube folder
      shell: ls -ltra ~/.kube/
      register: dir_contents

    - name: Retrieve helm binary archive
      unarchive:
        src: https://get.helm.sh/helm-v3.2.1-linux-amd64.tar.gz
        dest: /tmp
        creates: /usr/local/bin/helm
        remote_src: yes

    - name: Move helm binary into place
      command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
      args:
        creates: /usr/local/bin/helm

    - name: Verify helm installation
      command: "helm version --client --short"
      changed_when: false
      tags:
        - Verify helm installation

    - name: Create a k8s namespace for hashicorp vault
      k8s:
        name: "{{ vault_namespace }}"
        api_version: v1
        kind: Namespace
        state: present
      ignore_errors: false

    - name: Changing the current context namespace to vault namespace
      shell: |
        KUBECONFIG={{ kubeconfig_file }} kubectl config set-context --current --namespace={{ vault_namespace }}

    - name: Vault Helm chart repo
      shell: |
        helm repo add hashicorp https://helm.releases.hashicorp.com
      tags:
        - hashicorp-vault
        - hashicorp-vault-helm
        - aais-hashicorp-vault

    - name: Install vault helm chart
      shell: |
        helm --namespace={{ vault_namespace }} install {{ vault_helmchart_name }} hashicorp/vault \
        --set server.ha.enabled={{ vault_server_ha_enabled }} \
        --set server.ha.raft.enabled={{ vault_server_ha_raft_enabled }} \
        --set tlsDisable={{ vault_tlsDisable }} \
        --set server.ingress.enabled={{ vault_server_ingress_enabled }} \
        --set server.ingress.hosts[0].host={{ vault_server_ingress_hosts0_host }} \
        --set server.ingress.annotations."kubernetes\.io/ingress\.class"={{ vault_server_ingress_annotations_kubernetes_io_ingress_class }} \
        --set server.dataStorage.storageClass={{ vault_server_dataStorage_storageClass }}
      environment:
        - VAULT_SEAL_TYPE={{ vault_seal_type }}
        - VAULT_AWSKMS_SEAL_KEY_ID={{ vault_kms_key_id }}
      tags:
        - hashicorp-vault
        - hashicorp-vault-helm
        - aais-hashicorp-vault

    - name: delete kube config
      file:
        path: ~/.kube/config
        state: absent